// Update with your config settings.
module.exports = {

  development: {
    client: 'sqlite3',
    connection: {
      filename: './data/superhero.db3', //Specify the filename
    },
    // necessary when using sqlite3
    useNullAsDefault: true,

    migrations: {
      directory: './data/migrations', // Specify the location where migrations will be created
    },

    seeds: {
      directory: './data/seeds', // Specify where the seeds will be saved
    }
  }

};

// This file is automatically generated when we use npx knex init command on the command line
